### ISSUE TITLE
Missing squish module on enable

### ISSUE THREAD

**Issue by shanepaton** [Astral-C/Luigis-Mansion-Blender-Toolkit#1]
Hello,

I am having an issue when trying to install the plugin from the releases tab when it throws the error 
```ModuleNotFoundError: No module named 'squish'```.
When I checked the plugin folder there is a copy of squish.pyd. Am I doing something wrong like missing an instruction or installation or is a problem with the plugin or my version?

<img src="https://i.imgur.com/lhatUq7l.png"></img>
(Using Blender 3.2.2 on Windows 11)

Thanks

**Comment by AntonioAntonio-ai** [comment]
Use Blender version 2.8.3 LTS

**Comment by Astral-C** [comment]
The above is not guaranteed to work and is not entirely accurate.

This issue has been resolved as squish has been removed as a dependency.
